SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20 #pixels
ASTEROID_KINDS = 3 #Stages/Sizes of Asteroids
ASTEROID_SPAWN_RATE = 0.8 #Interval, seconds
ASTEROID_MAX_RADIUS = ASTEROID_KINDS * ASTEROID_MIN_RADIUS

PLAYER_RADIUS = 20 # pixels

