SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_SPAWN_INTERVAL = 0.8 # seconds
ASTEROID_KINDS = 3 # Stages/Sizes of Asteroids
ASTEROID_MIN_RADIUS = 20 # pixels
ASTEROID_MAX_RADIUS = ASTEROID_KINDS * ASTEROID_MIN_RADIUS # pixels

PLAYER_RADIUS = 20 # pixels
PLAYER_TURN_SPEED = 300 # degrees per second
PLAYER_MAX_SPEED = 200 # pixels per second
PLAYER_ACCELERATION = 500 # pixels per second per second
PLAYER_SHOOT_SPEED = 500 # pixels per second
PLAYER_SHOOT_COOLDOWN = 0.3 # seconds

SHOT_RADIUS = 5 # pixels
